application: serious-water-88716
version: 1
runtime: go
api_version: go1

handlers:
- url: /.*
  script: _go_app

pagespeed:
  domains_to_rewrite:
  - www.greatercommons.com
#  url_blacklist:
  enabled_rewriters:
  - MinifyCss
 # disabled_rewriters:
 # - ImageStripColorProfile
